__new method retrieves pointer and ID
utopia-rise/godot-kotlin-api-generator pull request #6
Opened 2021-03-15 17:16 UTC by CedNaru

Just a quick change so the ID is obtained at the same time as the pointer when calling "__new" so we don't have to call C++ a second time with 'getInstanceID()"

2021-03-15 17:38 UTC, chippmann approved these changes

2021-03-17 17:33 UTC, piiertho requested changes

2021-03-17 17:33 UTC, piiertho commented on src/main/kotlin/godot/codegen/Class.kt
> +                    .build())
I propose
```kotlin
            .addParameter(
                ParameterSpec.builder("classIndex", Int::class)
                    .build()
            )
```
Makes easier to read

2021-03-17 17:33 UTC, piiertho commented on src/main/kotlin/godot/codegen/Class.kt
> +            .addStatement(
I think we don't need line return here.

2021-03-17 17:33 UTC, piiertho commented on src/main/kotlin/godot/codegen/Class.kt
> +                "val buffer = TransferContext.buffer")
Litteral `TransferContext` should be replaced with %T and use of a `ClassName`

2021-03-18 10:26 UTC, piiertho approved these changes

2021-03-18 10:28 UTC, merged